### PR TITLE
Update mt8183 to v6.10.3

### PR DESCRIPTION
**Pull request by WeirdTreeThing**

### CODE REVIEW

**Comment by june-fish** [comment]
Has this been tested on hardware?

**Comment by WeirdTreeThing** [comment]
Don't remember, but probably only on krane

**Comment by WeirdTreeThing** [comment]
This PR needs to be updated to the latest kernel anyways

**Comment by june-fish** [comment]
Updated to latest kernel on my end and had @Owen-sz test, going to merge this PR then I'll push my update too. Thanks!

**Pull request merged**
